title: NLP for Peer Review
# description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

search_enabled: false

# url: https://just-the-docs.github.io

aux_links:
